services:
  - type: web
    name: healthyhearthelper
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y build-essential python3-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
